version: '3'

networks:
  app-bridge:
    driver: bridge

volumes:
  pgdata:
  pgadmin:

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - ${PORT}:${PORT}
    environment:
      NODE_ENV: development
      PORT: ${PORT}
      JWT_SECRET_KEY: ${JWT_SECRET_KEY}
      DATABASE_URL: ${DATABASE_URL}
    restart: on-failure
    networks:
      - app-bridge

  postgres:
    container_name: postgres
    build:
      context: .
      dockerfile: ./Dockerfile.postgres
    ports:
      - '5434:5432'
    volumes:
      - pgdata:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: ${POSTGRES_USERNAME}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DATABASE}
    networks:
      - app-bridge

  pgadmin:
    image: dpage/pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: ${PGADMIN_DEFAULT_EMAIL}
      PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_DEFAULT_PASSWORD}
    ports:
      - ${PGADMIN_PORT}:80
    volumes:
      - pgadmin:/var/lib/pgadmin
    depends_on:
      - postgres
    networks:
      - app-bridge

